// LimmConfig.swift — limm VPN constants + per-device UID
// Token is injected at build time via LimmSecrets.swift (gitignored, generated by CI).

import Foundation

enum LimmConfig {
    // API
    static let apiBase      = "https://limm.space/api"
    static let subURL       = "https://limm.space/vpn/sub"
    // proxy-vpn fork (V2rayU-based) has its own info file: proxy-mac-info.json.
    // Hiddify fork (vpn-mac) uses /vpn/mac/latest. Do NOT mix them up.
    static let releasesURL  = "https://limm.space/vpn/proxy-mac/latest"

    // Update/download mirrors in priority order: direct origin (www, grey-cloud → RU1 IP)
    // first, then Cloudflare. An ISP may block one path while the other stays reachable, so
    // the version-check and the .dmg download try both. www.limm.space bypasses CF; both
    // serve identical /vpn/* on RU1.
    static let updateHosts = ["www.limm.space", "vpn.limm.space", "limm.space"]
    private static let mirrorHostSet: Set<String> = ["limm.space", "www.limm.space", "vpn.limm.space"]

    /// Mirrors a limm download URL across all hosts (direct www first, then vpn via Bunny CDN,
    /// then bare limm via Cloudflare). Non-limm or unparseable URLs are returned unchanged.
    static func mirrorURLs(_ url: String) -> [String] {
        guard let comps = URLComponents(string: url), let host = comps.host,
              mirrorHostSet.contains(host) else { return [url] }
        return updateHosts.compactMap { h -> String? in
            var c = comps
            c.host = h
            return c.string
        }
    }

    /// Version-check endpoint mirrored across all hosts (direct www first).
    static var releasesURLs: [String] { mirrorURLs(releasesURL) }

    /// Subscription endpoint mirrored across all hosts (direct www first, then vpn+Bunny,
    /// then bare limm+CF). A blocked CF edge no longer stops the server list from refreshing.
    static var subURLs: [String] { mirrorURLs(subURL) }

    /// True if a /vpn/sub response body is a real subscription, not a provider block-page
    /// served with HTTP 200. Accepts base64 (the normal form) or already-decoded bodies.
    /// Rejecting a bad body is critical — importing it would wipe working servers.
    static func isValidSub(_ body: String) -> Bool {
        let trimmed = body.trimmingCharacters(in: .whitespacesAndNewlines)
        if trimmed.count < 8 { return false }
        let lower = trimmed.lowercased()
        if lower.contains("<html") || lower.contains("<!doctype") || lower.contains("<body") {
            return false
        }
        func hasScheme(_ s: String) -> Bool {
            return s.contains("vless://") || s.contains("vmess://") ||
                   s.contains("hysteria2://") || s.contains("hy2://") || s.contains("trojan://")
        }
        if hasScheme(trimmed) { return true }
        let compact = trimmed.replacingOccurrences(of: "\n", with: "")
                             .replacingOccurrences(of: "\r", with: "")
        if let data = Data(base64Encoded: compact),
           let decoded = String(data: data, encoding: .utf8), hasScheme(decoded) {
            return true
        }
        return false
    }

    // Checkin
    static let checkinInterval: TimeInterval = 900   // 15 min
    static let clientKind   = "macos"
    static let clientLabel  = "pc"
    // format "version+hash4" — parsed by dashboard buildTag() → shows #hash
    static let appVersion   = "\(LimmBuildInfo.version)+\(LimmBuildInfo.commit)"

    // Server (for L0-L2 raw probes)
    static let serverIP     = "45.95.175.170"
    static let serverPort   = 443

    // All known node egress IPs (FR1 + DE1). Egress-IP "is this our VPN?" checks must
    // accept ANY node, not just serverIP — otherwise DE1 profiles get a false "not VPN".
    static let serverIPs: Set<String> = ["45.95.175.170", "77.90.52.123"]
    static func isOurEgress(_ ip: String) -> Bool { serverIPs.contains(ip) }

    // UserDefaults keys
    static let uidKey            = "limmClientUID"
    static let checkinEnabledKey = "limmCheckinEnabled"
    static let autoServerKey      = "limmAutoServer"       // Bool — auto-switch enabled
    static let switchGapKey       = "limmAutoSwitchGap"   // String — gap threshold in ms (default "50")
    static let switchCooldownKey  = "limmAutoSwitchCooldown" // String — min minutes between switches (default "5")
    static let failedProfilesKey  = "limmFailedProfiles"   // [String] — server names that failed Full Test; skipped by auto-switch
    static let autoConnectKey     = "limmAutoConnect"       // Bool — auto-start VPN on app launch
    static let lastUpdateCheckKey = "limmLastUpdateCheck"  // Double — unix timestamp of last update check

    // Stable per-device UUID (auto-generated on first launch)
    static func clientUID() -> String {
        let d = UserDefaults.standard
        if let uid = d.string(forKey: uidKey), !uid.isEmpty { return uid }
        let uid = UUID().uuidString.lowercased()
        d.set(uid, forKey: uidKey)
        return uid
    }

    // Build-time token from LimmSecrets.swift
    static var token: String { LimmSecrets.monitorToken }
}
