// LimmConfig.swift — limm VPN constants + per-device UID
// Token is injected at build time via LimmSecrets.swift (gitignored, generated by CI).

import Foundation

enum LimmConfig {
    // API
    static let apiBase      = "https://limm.space/api"
    static let subURL       = "https://limm.space/vpn/sub"
    static let releasesURL  = "https://api.github.com/repos/lexx633/vpn-mac/releases/latest"

    // Checkin
    static let checkinInterval: TimeInterval = 900   // 15 min
    static let clientKind   = "macos"
    static let clientLabel  = "limm-mac"
    static let appVersion   = "v2rayu-1.0-limm"

    // Server (for L0-L2 raw probes)
    static let serverIP     = "45.95.175.170"
    static let serverPort   = 443

    // UserDefaults keys
    static let uidKey            = "limmClientUID"
    static let checkinEnabledKey = "limmCheckinEnabled"

    // Stable per-device UUID (auto-generated on first launch)
    static func clientUID() -> String {
        let d = UserDefaults.standard
        if let uid = d.string(forKey: uidKey), !uid.isEmpty { return uid }
        let uid = UUID().uuidString.lowercased()
        d.set(uid, forKey: uidKey)
        return uid
    }

    // Build-time token from LimmSecrets.swift
    static var token: String { LimmSecrets.monitorToken }
}
